# path:
ckpt: # will be overwrite
save_img_path: "./sample_videos/" # will be overwrite
pretrained_model_path: "/path/to/pretrained/Latte/"

# model config: 
model: Latte-XL/2
num_frames: 16
image_size: 256 # choices=[256, 512]
frame_interval: 2
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation
num_classes:

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed:
sample_method: 'ddpm'
num_sampling_steps: 250
cfg_scale: 1.0
run_time: 12
num_sample: 1
negative_name:

# ddp sample config
per_proc_batch_size: 1
num_fvd_samples: 2